### ISSUE TITLE
ClassCastException:TintContextWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by KKChong** [florent37/ViewTooltip#12]
Hi,
Im using OnePlus, OS version 4.4.4

Got this error: 
java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to android.app.Activity
at com.github.florent37.viewtooltip.ViewTooltip.show(ViewTooltip.java:59)
at com.rhb.mobile.rhb_cambodia.SecretWordActivity.showTooltips(SecretWordActivity.java:146)

**Comment by florent37** [comment]
try with v1.0.6 ;)
