### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by jonahollman** [florent37/ViewTooltip#66]
When attempting to show a tooltip, I get this error:

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/NestedScrollView

Here is my code:

    toolTip = ViewTooltip
         .on(holder.flareifiedIcon)
         .autoHide(false, 1000)
         .clickToHide(true)
         .corner(16)
         .position(ViewTooltip.Position.BOTTOM)
         .customView(tooltipView)
         .onDisplay {
             toolTipShowing = true
         }
         .onHide {
             if (tooltipView.parent != null) {
                 (tooltipView.parent as ViewGroup).removeView(tooltipView)
                 toolTipShowing = false
             } 
         }
    toolTip!!.show()

**Comment by pavelv99** [comment]
The same error

**Comment by mdvarga** [comment]
Ditto:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/NestedScrollView;
        at com.github.florent37.viewtooltip.ViewTooltip.findScrollParent(ViewTooltip.java:95)
        at com.github.florent37.viewtooltip.ViewTooltip.<init>(ViewTooltip.java:46)
        at com.github.florent37.viewtooltip.ViewTooltip.on(ViewTooltip.java:77)
```

**Comment by mdvarga** [comment]
Looks like this issue is related to this library using AndroidX for version 1.2.x - and the project that I'm working on hasn't migrated to use AndroidX yet.

I reverted to use 1.1.8 (i.e. pre-AndroidX) and the library is working fine now.

**Comment by PankajS24** [comment]
What if we want to use it with Android X?
